#!/usr/bin/env python3
"""Turn a raw 6502 binary into a C header for the firmware's built-in demo.

usage: bin2c.py PROGRAM.bin LOAD_ADDR > src/demo_program.h
"""
import os
import sys

if len(sys.argv) != 3:
    sys.exit(__doc__.strip())

path = sys.argv[1]
addr = int(sys.argv[2].lstrip("$"), 16)
with open(path, "rb") as f:
    data = f.read()

print(f"// Generated by tools/bin2c.py from {os.path.basename(path)}; do not edit.")
print("#pragma once")
print("#include <stdint.h>")
print()
print(f"#define DEMO_LOAD_ADDR 0x{addr:04X}")
print()
print("static const uint8_t demo_program[] = {")
for i in range(0, len(data), 12):
    print("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 12]) + ",")
print("};")
